spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest-with-spring-boot?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    #properties:
      #hibernate:
       # dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: false
    open-in-view: false
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true